### ISSUE TITLE
unable to find recipe1m module

### ISSUE THREAD

**Issue by PietropaoloV** [mshukor/TFood#1]
Hello I am trying to run the training portion of the code. When I go to run the code with the scripts you provided I get the following results from bootstrap.run.

...torch/bootstrap/run.py.198: Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/Code/TFood-main/bootstrap.pytorch/bootstrap/run.py", line 183, in main
    run(path_opts=path_opts, rank=rank)
  File "/content/drive/MyDrive/Colab Notebooks/Code/TFood-main/bootstrap.pytorch/bootstrap/run.py", line 88, in run
    engine.dataset = datasets.factory(engine)
  File "/content/drive/MyDrive/Colab Notebooks/Code/TFood-main/bootstrap.pytorch/bootstrap/datasets/factory.py", line 14, in factory
    module = importlib.import_module(Options()['dataset']['import'])
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'recipe1m'

Is there a specific directory I should reside in inorder to run the code?

**Comment by mshukor** [comment]
Hello, I just tried to launch the training in a notebook and didn't get the same error. Can you try launching the training from the tfood/ directory? where you have the recipe1m folder (and thus the options path will be recipe1m/options/tfood_clip.yaml):

```
python -m bootstrap.run -o recipe1m/options/tfood_clip.yaml --misc.data_parrallel true
```

If this didn't work you may need to add explicitly the path to recipe1m:
```
import sys
sys.path.append("path/to/tfood/")
```
