### ISSUE TITLE
a bug in TFood

### ISSUE THREAD

**Issue by Acura-bit** [mshukor/TFood#8]
Hello, it's My Phoenix here. I'm now running the TFood codes[https://github.com/mshukor/TFood] in your paper. When I launch the training procedure, the epoch 0 can successfully train on trainset and validate on valset. However, the following epoch 1 can't keep  going on, a bug "TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'" occurs. The logs are below:

```
[I 2023-05-19 16:54:16] ...tstrap/views/plotly.py.125: Plotly view generated in /root/autodl-tmp/root/logs/view.html
[I 2023-05-19 16:54:21] [...trap/engines/engine.py.451:](http://...trap/engines/engine.py.451:) Saving optimizer...
[I 2023-05-19 16:54:28] [...trap/engines/engine.py.455:](http://...trap/engines/engine.py.455:) Saving engine...
[I 2023-05-19 16:54:28] [...trap/engines/engine.py.170:](http://...trap/engines/engine.py.170:) Training model on trainset for epoch 1
[I 2023-05-19 16:54:28] ...m/datasets/recipe1m.py.294: Dataset will be sampled with "triplet_classif" batch_sampler.
[E 2023-05-19 16:54:29] ...torch/bootstrap/run.py.213: Traceback (most recent call last):
  File "/root/TFood/bootstrap.pytorch/bootstrap/run.py", line 193, in main
    run(path_opts=path_opts, rank=rank)
  File "/root/TFood/bootstrap.pytorch/bootstrap/run.py", line 120, in run
    engine.train()
  File "/root/TFood/bootstrap.pytorch/bootstrap/engines/engine.py", line 133, in train
    self.train_epoch(self.model, self.dataset['train'], self.optimizer, self.epoch)
  File "/root/TFood/bootstrap.pytorch/bootstrap/engines/engine.py", line 185, in train_epoch
    for i, batch in enumerate(batch_loader):
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 303, in __getitem__
    item['recipe'] = self.recipes_dataset[index]
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 215, in __getitem__
    item = self.get_recipe(index)
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 232, in get_recipe
    tokenized_ingrs = [l + (max_len - len(l))*[0] for l in tokenized_ingrs]
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 232, in <listcomp>
    tokenized_ingrs = [l + (max_len - len(l))*[0] for l in tokenized_ingrs]
TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'
```

Could you please give me some advice. Thanks in advance.

**Comment by Acura-bit** [comment]
# Modify some files

I follow the readme to conduct the experiment. And I just modify codes in some file which report errors in my Pycharm:

* `recipe1m/models/metrics/trijoint.py`: I delete the line 9 "from recipe1m.models.networks.recipe_networks.networks import AvgPoolSequence" because I don't find `AvgPoolSequence` in  "recipe1m.models.networks.recipe_networks.networks"

* `recipe1m/models/networks/trijoint.py`: I delete `AvgPoolSequence` in line 12

* `recipe1m/visu/old_top5.py`: In line 12, I don't find `Trijoint` in "recipe1m.models.networks.trijoint", so I change it to "from recipe1m.models.trijoint import Trijoint"

* `recipe1m/visu/old_top5_old.py`: In line 18, I find `imsave` has never been used, so I delete line 18.

  ![image-20230520165528300](https://cdn.jsdelivr.net/gh/Acura-bit/imagebed@main/image-20230520165528300.png)

* `recipe1m/visu/old_tsne.py`: I delete the line 13, because I find the `imsave` has never been used. 



And I changed some paths in the `tfood_clip.yaml` file :

```python
__include__: abstract.yaml
exp:
    dir: /root/autodl-tmp/root/logs/
dataset:
    batch_size: 100
    dir: /root/autodl-tmp/root/
    import: TFood.recipe1m.datasets.factory
    freq_mismatch: 0.0
    tokenized_raw_text: True
    nb_threads: 0
model:
    import: TFood.recipe1m.models.factory
    with_classif: False
    network:
        image_backbone_name: clip
        recipe_encoder: h-transformer
        n_heads: 4
        n_layers: 2
        n_layers_single: 2
        n_heads_single: 4
        old: True
        # Note:I dont't find the vocab.pkl file, I just use the pkl file generated in VLPCook. 
        # I don't know whether it's reasonable.
        path_ingrs: /root/autodl-tmp/root/text/vocab.pkl 
        path_vocab: /root/autodl-tmp/root/vocab_all.txt
        hidden_size: 512
        with_titles: True

        cross_transformer: False
        cross_decoder_recipe: True
        avg_concat: True
        n_layers_cross: 2
        n_heads_cross: 4
        get_tokens_cross_decoder_recipe: True

        cross_decoder_image: True
        # context_image: 1 # 0 title, 1 ingrds, 2 instrs
        n_heads_cross_image: 4
        n_layers_cross_image: 1

        class_attention: False
        cls_token: False
        class_attention_fus: False
        cls_token_fus: False
        get_tokens: True
        freeze_rec: False 
        freeze_im: False
        vit_all_tokens: True
        cross_encoder: True
        cross_encoder_params:
            cross_decoder: True
            query_img: False
            double_decoder: False
            cross_attention: False
            n_heads: 4
            n_layers: 4    
            class_attention: False
            cls_token: False
            get_tokens: False
            load_backbones: False
    criterion:
        name: trijoint
        keep_background: False
        retrieval_strategy:
            name: triplet # quadruplet, triplet, pairwise, or pairwise_pytorch
            margin: 0.18
            margin_params:
                increment_margin: True
                increment: 0.005
                max_margin: 0.3
            sampling: max_negative # random (outdated), max_negative, or prob_negative
            nb_samples: 9999
            aggregation: valid # mean, valid (adamine)
            substrategy:
                - IRR
                - RII
                - SIRR
                - SRII
            substrategy_weights:
                - 1.0
                - 1.0
                - 0.1
                - 0.1
            get_tokens: True

        cross_encoder: True
        itm_loss_weight: 1
        cross_encoder_params:
            tri_cross_encoder: False
    metric:
        k_test: 10
        retrieval_dir: /root/autodl-tmp/root/ret
        trijoint: True
misc:
    cuda: True
    seed: 1338
    logs_name:
    overrite: False
    data_parrallel: False

optimizer:
    lr_img: 0.000001
    lr: 0.00001
    import: TFood.recipe1m.optimizers.factory
engine:
    nb_epochs: 120
```

> Note: I just modify some python files and  tfood_clip.yaml described as above.

# Start experiment

1、I use the env.yaml file in the TFood project to create my conda environment "tfood". And then I install the `bootstrap.pytorch` and `clip` successfully.

2、I execute the command `python preprocess/create_tokenized_layer.py --path_layer root/layer1.json --output_path_vocab root/vocab_all.txt --output_path_layer1 root/tokenized_layer_1.json --output_path_tokenized_texts root/text`  to tokenized layer1. And the 3 files are created: 

![image-20230520161917138](https://cdn.jsdelivr.net/gh/Acura-bit/imagebed@main/image-20230520161917138.png)

> Questions: 
>
> * Are the files generated above correct?
> * I wonder if I missed some files which may be used by the codes during training.

After that, I execute the command `python preprocess/h5py_to_lmdb.py --dir_data root` to create the lmdb file:

![image-20230520162029226](https://cdn.jsdelivr.net/gh/Acura-bit/imagebed@main/image-20230520162029226.png)

And then I download `classes1M.pkl`, and place the file in `root`

3、I start training the model with 2 Tesla V100-PCIE-32GB GPSs by execute the command `CUDA_VISIBLE_DEVICES=0,1 python -m bootstrap.run -o options/tfood_clip.yaml --misc.data_parrallel true` 



The epoch 0 successfully finished on trainset and valset. However, a error named `TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'` occurs before the epoch 1. The logs are below:

```python
[I 2023-05-19 16:54:15] ...trap/engines/engine.py.148: Saving last checkpoint
[I 2023-05-19 16:54:15] ...trap/engines/engine.py.447: Saving model...
[W 2023-05-19 16:54:15] ...otstrap/views/plotly.py.87: View 'train_epoch.bad_pairs' not in 'logs.json'
[W 2023-05-19 16:54:15] ...otstrap/views/plotly.py.93: Split 'optimizer' not in colors '['train_epoch', 'train_batch', 'val_epoch', 'val_batch', 'eval_epoch', 'eval_batch', 'test_epoch', 'test_batch', 'eval_pruned_epoch', 'eval_pruned_batch']'
[W 2023-05-19 16:54:15] ...otstrap/views/plotly.py.93: Split 'optimizer' not in colors '['train_epoch', 'train_batch', 'val_epoch', 'val_batch', 'eval_epoch', 'eval_batch', 'test_epoch', 'test_batch', 'eval_pruned_epoch', 'eval_pruned_batch']'
[I 2023-05-19 16:54:16] ...tstrap/views/plotly.py.125: Plotly view generated in /root/autodl-tmp/root/logs/view.html
[I 2023-05-19 16:54:21] ...trap/engines/engine.py.451: Saving optimizer...
[I 2023-05-19 16:54:28] ...trap/engines/engine.py.455: Saving engine...
[I 2023-05-19 16:54:28] ...trap/engines/engine.py.170: Training model on trainset for epoch 1
[I 2023-05-19 16:54:28] ...m/datasets/recipe1m.py.294: Dataset will be sampled with "triplet_classif" batch_sampler.
[E 2023-05-19 16:54:29] ...torch/bootstrap/run.py.213: Traceback (most recent call last):
  File "/root/TFood/bootstrap.pytorch/bootstrap/run.py", line 193, in main
    run(path_opts=path_opts, rank=rank) 
  File "/root/TFood/bootstrap.pytorch/bootstrap/run.py", line 120, in run
    engine.train() 
  File "/root/TFood/bootstrap.pytorch/bootstrap/engines/engine.py", line 133, in train
    self.train_epoch(self.model, self.dataset['train'], self.optimizer, self.epoch)
  File "/root/TFood/bootstrap.pytorch/bootstrap/engines/engine.py", line 185, in train_epoch
    for i, batch in enumerate(batch_loader):
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/tfood/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 303, in __getitem__
    item['recipe'] = self.recipes_dataset[index]
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 215, in __getitem__
    item = self.get_recipe(index)
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 232, in get_recipe
    tokenized_ingrs = [l + (max_len - len(l))*[0] for l in tokenized_ingrs]
  File "/root/TFood/recipe1m/datasets/recipe1m.py", line 232, in <listcomp>
    tokenized_ingrs = [l + (max_len - len(l))*[0] for l in tokenized_ingrs]
TypeError: unsupported operand type(s) for +: 'Tensor' and 'list'
```



Could you please give me some advice? I'm now engaged in research with cross-modal image retrieval and I really really want to repeat your experiment. Thanks in advance!!!
